services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cep
      - POSTGRES_USER=testeUser
    ports:
      - 5432:5432
